openapi: 3.0.1
info:
  title: PersistenceExampleService
  version: 2018-12-19
servers:
- url: /
paths:
  /customers:
    get:
      operationId: ListCustomers
      parameters:
      - name: maximumPageSize
        in: query
        schema:
          type: integer
      - name: nextPageToken
        in: query
        schema:
          type: string
      responses:
        200:
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCustomersResponse'
        404:
          description: 404 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownResourceFault'
      security:
      - sigv4: []
      x-amazon-apigateway-integration:
        responses:
          200:
            statusCode: "200"
          400:
            statusCode: "400"
        uri: http://${stageVariables.LoadBalancerDNSName}:8080/customer
        passthroughBehavior: when_no_templates
        connectionType: VPC_LINK
        connectionId: ${stageVariables.VpcLinkId}
        httpMethod: GET
        type: http
    put:
      operationId: CreateCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCustomerRequest'
        required: true
      responses:
        200:
          description: 200 response
          headers:
            X-Request-ID:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
        404:
          description: 404 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownResourceFault'
      security:
      - sigv4: []
      x-amazon-apigateway-integration:
        responses:
          200:
            statusCode: "200"
          400:
            statusCode: "400"
        uri: http://${stageVariables.LoadBalancerDNSName}:8080/customer
        passthroughBehavior: when_no_templates
        connectionType: VPC_LINK
        connectionId: ${stageVariables.VpcLinkId}
        httpMethod: PUT
        type: http
      x-codegen-request-body-name: CreateCustomerRequest
  /customer/{id}:
    get:
      operationId: GetCustomerDetails
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: includeOnlyPrimaryEmail
        in: query
        schema:
          type: string
      - name: X-Request-ID
        in: header
        schema:
          type: string
      responses:
        200:
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerAttributes'
        404:
          description: 404 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownResourceFault'
      security:
      - sigv4: []
      x-amazon-apigateway-integration:
        responses:
          200:
            statusCode: "200"
          400:
            statusCode: "400"
        uri: http://${stageVariables.LoadBalancerDNSName}:8080/customer/{id}
        passthroughBehavior: when_no_templates
        connectionType: VPC_LINK
        connectionId: ${stageVariables.VpcLinkId}
        httpMethod: GET
        type: http
  /customer/{id}/email:
    put:
      operationId: AddCustomerEmailAddress
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
              - emailAddress
              - notifyOnAllActions
              - notifyOnImportantAction
              type: object
              properties:
                emailAddress:
                  type: string
                isPrimary:
                  type: boolean
                notifyOnImportantAction:
                  type: boolean
                notifyOnAllActions:
                  type: boolean
        required: false
      responses:
        200:
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerEmailAddressIdentity'
        400:
          description: 400 response
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/CustomerEmailAddressLimitExceededFault"
                  - $ref: "#/components/schemas/CustomerEmailAddressAlreadyExistsFault"
        404:
          description: 404 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnknownResourceFault'
        409:
          description: 409 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrencyFault'
      security:
      - sigv4: []
      x-amazon-apigateway-integration:
        responses:
          200:
            statusCode: "200"
          400:
            statusCode: "400"
        uri: http://${stageVariables.LoadBalancerDNSName}:8080/customer/{id}/email
        passthroughBehavior: when_no_templates
        connectionType: VPC_LINK
        connectionId: ${stageVariables.VpcLinkId}
        httpMethod: PUT
        type: http
      x-codegen-request-body-name: addDetails
components:
  schemas:
    BirthYear:
      type: integer
    ConcurrencyFault:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
    CoreCustomerAttributes:
      required:
      - birthYear
      - firstName
      - lastName
      type: object
      properties:
        firstName:
          $ref: '#/components/schemas/FirstName'
        lastName:
          $ref: '#/components/schemas/LastName'
        birthYear:
          $ref: '#/components/schemas/BirthYear'
        gender:
          $ref: '#/components/schemas/Gender'
    CreateCustomerRequest:
      required:
      - birthYear
      - firstName
      - lastName
      type: object
      properties:
        firstName:
          $ref: '#/components/schemas/FirstName'
        lastName:
          $ref: '#/components/schemas/LastName'
        birthYear:
          $ref: '#/components/schemas/BirthYear'
        gender:
          $ref: '#/components/schemas/Gender'
    CustomerAttributes:
      required:
      - birthYear
      - emailAddresses
      - firstName
      - lastName
      type: object
      properties:
        firstName:
          $ref: '#/components/schemas/FirstName'
        lastName:
          $ref: '#/components/schemas/LastName'
        birthYear:
          $ref: '#/components/schemas/BirthYear'
        gender:
          $ref: '#/components/schemas/Gender'
        emailAddresses:
          $ref: '#/components/schemas/CustomerEmailAddressAttributesList'
    CustomerEmailAddressAttributes:
      required:
      - emailAddress
      - notifyOnAllActions
      - notifyOnImportantAction
      type: object
      properties:
        emailAddress:
          $ref: '#/components/schemas/CustomerEmailAddress'
        notifyOnImportantAction:
          $ref: '#/components/schemas/NotifyOnImportantAction'
        notifyOnAllActions:
          $ref: '#/components/schemas/NotifyOnAllActions'
    CustomerEmailAddressAttributesList:
      type: array
      items:
        $ref: '#/components/schemas/CustomerEmailAddressAttributes'
    CustomerEmailAddressIdentity:
      required:
      - id
      type: object
      properties:
        id:
          $ref: '#/components/schemas/CustomerEmailAddress'
    CustomerEmailAddressAlreadyExistsFault:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
    CustomerEmailAddressLimitExceededFault:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
    CustomerEmailAddress:
      maxLength: 254
      minLength: 1
      type: string
    CustomerID:
      maxLength: 150
      minLength: 1
      type: string
    CustomerIDList:
      type: array
      items:
        $ref: '#/components/schemas/CustomerID'
    CustomerIdentity:
      required:
      - id
      type: object
      properties:
        id:
          $ref: '#/components/schemas/CustomerID'
    ErrorMessage:
      type: string
    FirstName:
      maxLength: 300
      minLength: 1
      type: string
    Gender:
      type: string
      enum:
      - FEMALE
      - MALE
      - OTHER
    LastName:
      maxLength: 300
      minLength: 1
      type: string
    ListCustomersResponse:
      required:
      - customerIDs
      type: object
      properties:
        customerIDs:
          $ref: '#/components/schemas/CustomerIDList'
        nextPageToken:
          $ref: '#/components/schemas/NextPageToken'
    NextPageToken:
      maxLength: 2048
      minLength: 1
      type: string
    NotifyOnAllActions:
      type: boolean
    NotifyOnImportantAction:
      type: boolean
    UnknownResourceFault:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/ErrorMessage'
  securitySchemes:
    sigv4:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: awsSigv4
