version: "3.8"
services:

  backend:
    build:
      context: ..
      dockerfile: development/backend-${target}/dev.dockerfile
    environment:
      MYSQL_HOST: mysql-backend
      MYSQL_PORT: 3306
      MYSQL_DBNAME: isucondition
      MYSQL_USER: isucon
      MYSQL_PASS: isucon
      POST_ISUCONDITION_TARGET_BASE_URL: "http://isucondition-1.t.isucon.dev"
    entrypoint: dockerize -wait tcp://mysql-backend:3306 -timeout 60s
    command: air -c /development/air.toml
    ports:
      - "3000:3000"
    volumes:
      - "../webapp/go:/webapp/go"
      - "../webapp/ec256-public.pem:/webapp/ec256-public.pem"
      - "../webapp/NoImage.jpg:/webapp/NoImage.jpg"
      # SQLs
      - "../webapp/sql/init.sh:/webapp/sql/init.sh"
      - "../webapp/sql/0_Schema.sql:/webapp/sql/0_Schema.sql"
      - "../webapp/sql/1_InitData.sql:/webapp/sql/1_InitData.sql"
    depends_on:
      - mysql-backend

  mysql-backend:
    build:
      context: .
      dockerfile: mysql-backend/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: isucondition
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      MYSQL_ROOT_PASSWORD: root
    volumes:
      # 開発環境用のものを使って初期化
      - "../webapp/sql/0_Schema.sql:/docker-entrypoint-initdb.d/0_Schema.sql"
      - "../development/mysql-backend/1_Constraint.sql:/docker-entrypoint-initdb.d/1_Constraint.sql"
      - "../development/mysql-backend/2_Init.sql:/docker-entrypoint-initdb.d/2_Init.sql"
    expose:
      - "3306"
    ports:
      - "3306:3306"

  apitest:
    build:
      context: ..
      dockerfile: development/apitest/dev.dockerfile
    environment:
      ISUXBENCH_TARGET: backend:3000
      ISUXBENCH_ALL_ADDRESSES: backend
    working_dir:  /bench_dir
    entrypoint: bash
    tty: true
    volumes:
      - "../bench:/bench_dir"
    depends_on:
      - mysql-backend
      - backend
