backend:
  - webapp/go/**/*
frontend:
  - webapp/frontend/**/*
benchmarker:
  - bench/**/*
infrastructure:
  - provisioning/**/*
documentation:
  - docs/**/*
transplant:
  - webapp/nodejs/**/*
  - webapp/perl/**/*
  - webapp/php/**/*
  - webapp/python/**/*
  - webapp/ruby/**/*
  - webapp/rust/**/*
initial-data:
  - extra/initial-data/**/*
  - bench/random/**/*
jiaapi-mock:
  - extra/jiaapi-mock/**/*
