---
- name: "roles/contestant/tasks/jiaapi_mock: Deploy tls certs (*.t.isucon.dev)"
  become_user: root
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0755"
  with_items:
    - tmp/isucon11-qualify/extra/jiaapi-mock/jiaapi-mock/tls-cert.pem
    - tmp/isucon11-qualify/extra/jiaapi-mock/jiaapi-mock/tls-key.pem

- name: "roles/contestant/tasks/jiaapi_mock: Build jiaapi-mock"
  become_user: isucon
  args:
    chdir: /tmp/isucon11-qualify/extra/jiaapi-mock
  environment:
    PATH: "/home/isucon/local/go/bin:{{ ansible_env.PATH }}"
  command: make

- name: "roles/contestant/tasks/jiaapi_mock: Deploy jiaapi-mock"
  become_user: root
  copy:
    remote_src: yes
    src: /tmp/isucon11-qualify/extra/jiaapi-mock/jiaapi-mock
    dest: /usr/local/bin/
    owner: "root"
    group: "root"
    mode: "0755"

- name: "roles/contestant/tasks/jiaapi_mock: Deploy Service file"
  become_user: root
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - etc/systemd/system/jiaapi-mock.service

- name: "roles/contestant/tasks/jiaapi_mock: Enable jiaapi-mock.service"
  become_user: root
  systemd:
    daemon_reload: "yes"
    name: "jiaapi-mock.service"
    enabled: "yes"

